"""empty message

Revision ID: ddc600fc9b3a
Revises: 5be9f7f85b1d
Create Date: 2023-02-13 12:02:07.636894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddc600fc9b3a'
down_revision = '5be9f7f85b1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=True))
        batch_op.drop_index('ix_user_userame')
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)
        batch_op.drop_column('userame')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userame', sa.VARCHAR(length=80), nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.create_index('ix_user_userame', ['userame'], unique=False)
        batch_op.drop_column('username')

    # ### end Alembic commands ###
